In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"C:\Users\M_dell\Downloads\titanic (1).csv")

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
grouped = df.groupby('Pclass')['Fare']
print(grouped)

<pandas.api.typing.SeriesGroupBy object at 0x0000025F11736F90>

In [6]:
summary = grouped.agg(['mean','median','min','max','std'])
print(summary)

             mean   median  min       max        std
Pclass
1       84.154687  60.2875  0.0  512.3292  78.380373
2       20.662183  14.2500  0.0   73.5000  13.417399
3       13.675550   8.0500  0.0   69.5500  11.778142

In [8]:
grouped_list = df.groupby('Pclass')['Fare'].apply(list)
print(grouped_list)

Pclass
1    [71.2833, 53.1, 51.8625, 26.55, 35.5, 263.0, 2...
2    [30.0708, 16.0, 13.0, 26.0, 13.0, 10.5, 21.0, ...
3    [7.25, 7.925, 8.05, 8.4583, 21.075, 11.1333, 1...
Name: Fare, dtype: object

In [9]:
for cls,values in grouped_list.items():
    print(values[:10])

[71.2833, 53.1, 51.8625, 26.55, 35.5, 263.0, 27.7208, 146.5208, 82.1708, 52.0]
[30.0708, 16.0, 13.0, 26.0, 13.0, 10.5, 21.0, 41.5792, 26.0, 10.5]
[7.25, 7.925, 8.05, 8.4583, 21.075, 11.1333, 16.7, 8.05, 31.275, 7.8542]

In [11]:
# part 2 iris dataset
dff = pd.read_csv(r"C:\Users\M_dell\Downloads\Iris.csv")
dff.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [13]:
iris_group = dff.groupby('Species')
iris_group.min()

                  Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa        1            4.3           2.3            1.0           0.1
Iris-versicolor   51            4.9           2.0            3.0           1.0
Iris-virginica   101            4.9           2.2            4.5           1.4

In [14]:
iris_group.max()
iris_group.std()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Species,,,,,
Iris-setosa,14.57738,0.352490,0.381024,0.173511,0.107210
Iris-versicolor,14.57738,0.516171,0.313798,0.469911,0.197753
Iris-virginica,14.57738,0.635880,0.322497,0.551895,0.274650